export var plans = [
  {
    id: "p001",
    name: "Basic DAM functionality",
    value: [true, true, true, true, true, true],
    details: [
      {
        id: "pd001",
        name: "Uploading",
        prompt: "Upload your assets into Pics.io library",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd002",
        name: "Searching",
        prompt:
          "Search for assets through your library with keywords and other metadata",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd003",
        name: "Downloading",
        prompt: "Download assets from your Pics.io library",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd004",
        name: "Version Control",
        prompt:
          "Keep more than one revision of a file, switch between  the revisions and approve the final version",
        value: [true, true, true, true, true, true],
      },
    ],
  },
  {
    id: "p002",
    name: "Your team and library",
    value: ["middle", "middle", "middle", "middle", "middle", true],
    details: [
      {
        id: "pd005",
        name: "Maximum size of the library, TB",
        prompt: "Total amount of space taken by all the assets in your library",
        value: [
          "infinity",
          "infinity",
          "infinity",
          "infinity",
          "infinity",
          "infinity",
        ],
      },
      {
        id: "pd006",
        name: "Maximum number of assets in the library",
        prompt: "Number of assets in your library",
        value: [
          "50K",
          "infinity",
          "infinity",
          "infinity",
          "infinity",
          "infinity",
        ],
      },
      {
        id: "pd007",
        name: "Number of teammates in the team included in the plan",
        prompt: "Number of user accounts on your plan",
        value: [
          false,
          "1 included $18/mo each additional",
          "10 included $18/mo each additional",
          "50 included $15/mo each additional",
          "100 included",
          "infinity",
        ],
      },
      {
        id: "pd008",
        name: "Branded look and feel",
        prompt:
          "Customize your Pics.io account with  your own colors, identities and connect  domain name for system pages like login",
        value: [false, false, false, true, true, true],
      },
    ],
  },
  {
    id: "p003",
    name: "Sharing and collaboration",
    value: ["middle", "middle", "middle", "middle", "middle", true],
    details: [
      {
        id: "pd009",
        name: "Commenting",
        prompt: "Your teammates can leave comments  and visual marks on your assets",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd010",
        name: "Number of public Websites",
        prompt: "Turn any collection from your  library into a website to share  with non-Pics.io users",
        value: [
          false,
          "0 included $12/mo each additional",
          "15 included $12/mo each additional",
          "50 included $10/mo each additional",
          "100 included",
          "infinity",
        ],
      },
      {
        id: "pd011",
        name: "Single asset sharing",
        prompt: "Share to non-Pics.io users  any single asset from your library",
        value: [false, 10, "infinity", "infinity", "infinity", "infinity"],
      },
      {
        id: "pd012",
        name: "Number of inboxes",
        prompt: "Allow non-Pics.io users to upload  new files into the separate  workspace within your library.",
        value: [false, false, 1, 5, 10, "infinity"],
      },
    ],
  },
  {
    id: "p004",
    name: "Storage Syncronization",
    value: ["middle", "middle", "middle", "middle", "middle", true],
    details: [
      {
        id: "pd013",
        name: "Manual",
        prompt: "Manual synchronization between  the connected storage and  your Pics.io library",
        value: [
          "Accessible every 60 minutes",
          "Accessible every 15 minutes",
          "Accessible at any time",
          "Accessible at any time",
          "Accessible at any time",
          "Accessible at any time",
        ],
      },
      {
        id: "pd014",
        name: "Automatic",
        prompt: "Automatic synchronization between  the connected storage and  your Pics.io library",
        value: [
          false,
          false,
          "Occurs every 30 minutes",
          "Occurs every 15 minutes",
          "Occurs every 5 minutes",
          "Occurs in real-time",
        ],
      },
    ],
  },
  {
    id: "p005",
    name: "Analytics & reporting",
    value: ["middle", "middle", "middle", "middle", "middle", true],
    details: [
      {
        id: "pd015",
        name: "Activity Logs",
        prompt: "The time period for keeping the  data about your activity within the system",
        value: ["1 day", "7 days", "1 month", "6 months", "1 year", "3 years"],
      },
      {
        id: "pd016",
        name: "Storage",
        prompt: "Statistics on your storage usage",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd017",
        name: "Library",
        prompt: "Statistics on how the library is transformed",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd018",
        name: "Websites",
        prompt: "Reports on the number of visitors  and assets downloaded on websites",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd019",
        name: "Teammate",
        prompt: "Statistics on the user's  activity within the account",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd020",
        name: "Team",
        prompt: "Statistics on the team  activity within the library",
        value: [false, false, false, true, true, true],
      },
      {
        id: "pd021",
        name: "Asset",
        prompt: "Statistics on how the asset  was used within the system",
        value: [false, false, false, true, true, true],
      },
      {
        id: "pd022",
        name: "Visual comparison tool",
        prompt: "Visually compare various  revisions of the same asset in Pics.io",
        value: [false, true, true, true, true, true],
      },
    ],
  },
  {
    id: "p006",
    name: "Metadata management",
    value: ["middle", true, true, true, true, true],
    details: [
      {
        id: "pd023",
        name: "Metadata fields management",
        prompt: "Change the default  metadata of your assets ",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd024",
        name: "EXIF/IPTC/XMP metadata reading & writing",
        prompt: "Capture the EXIF/IPTC/XMP  metadata within the digital asset,  and in case of changes save updated  meta information back to the original file",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd025",
        name: "Custom fields schema",
        prompt: "Create your own custom fields  depending on your team workflow.",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd026",
        name: "Automatic AI keywording for images",
        prompt: "Automatically attach keywords for  images using the computer vision.This function is free for the  first 1000 images.",
        value: [
          "$20/1000 images",
          "$20/1000 images",
          "$18/1000 images",
          "$15/1000 images",
          "$10/1000 images",
          "The cheapest AI keywording",
        ],
      },
    ],
  },
  {
    id: "p007",
    name: "Support",
    value: ["middle", "middle", "middle", "middle", "middle", true],
    details: [
      {
        id: "pd027",
        name: "Online knowledge base",
        prompt: "24/7 online access  to HelpCenter articles ",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd028",
        name: "Email",
        prompt: "Qualified customer support  through the email",
        value: ["72 hours turnaround", true, true, true, true, true],
      },
      {
        id: "pd029",
        name: "Online chat",
        prompt: "Qualified customer support  through the online chat",
        value: [false, "4 hours turnaround", true, true, true, true],
      },
      {
        id: "pd030",
        name: "Customer success manager",
        prompt: "Individual support by  customer success manager ",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd031",
        name: "Personal support engineer",
        prompt: "Individual technical support",
        value: [false, false, false, false, true],
      },
    ],
  },
  {
    id: "p008",
    name: "Integration with 3rd party tools and services",
    value: ["middle", "middle", true, true, true, true],
    details: [
      {
        id: "pd032",
        name: "Google Drive",
        prompt: "Integration with  Google Drive storage space",
        value: [true, true, true, true, true, true],
      },
      {
        id: "pd033",
        name: "Amazon S3",
        prompt: "Integration with Amazon storage space",
        value: [
          false,
          false,
          "Coming soon",
          "Coming soon",
          "Coming soon",
          "Coming soon",
        ],
      },
      {
        id: "pd034",
        name: "Slack ",
        prompt: "Get notifications on your  account changes within  the Slack team messenger.",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd035",
        name: "Zapier",
        prompt: "Integrate your Pics.io account  with your other favorite apps (Dropbox, Hubspot CRM, Facebook, etc.)  using Zapier app",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd036",
        name: "Webhooks",
        prompt: "Configure webhook URLs for  particular events happening  in your digital library and get  notifications to the required app.",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd037",
        name: "Google Docs",
        prompt: "Embed visual content from  your media library right into your  Google Docs and illustrate the shared document ",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd038",
        name: "Google Spreadsheets",
        prompt: "Embed visual content from  your media library right into  your Google Sheets and illustrate  the shared spreadsheet ",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd039",
        name: "Google Forms",
        prompt: "Embed visual content from  your media library into Google Forms  and illustrate the shared survey ",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd040",
        name: "Google Slides",
        prompt: "Embed visual content from  your Pics.io media library right into your Google Slides",
        value: [false, true, true, true, true, true],
      },
      {
        id: "pd041",
        name: "Adobe Photoshop",
        prompt: "Create a convenient shortcut  between your shared library and Photoshop workspace",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd042",
        name: "Adobe Illustrator",
        prompt: "Create a convenient shortcut  between your digital library and  Adobe Illustrator design workspace",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd043",
        name: "Adobe Premiere Pro",
        prompt: "Integrate your digital library  in Pics.io with the leading  video editing software - Adobe Premiere Pro",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd044",
        name: "Adobe After Effects",
        prompt: "Find & reuse your media  files without leaving Adobe CC  using Pics.io plug-in for Adobe After Effects",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd045",
        name: "Zoho CRM",
        prompt: "Easily attach digital assets from your Pics.io library to specific leads in Zoho CRM",
        value: [false, false, true, true, true, true],
      },
      {
        id: "pd046",
        name: "Wordpress",
        prompt: "",
        value: [
          false,
          false,
          "Coming soon",
          "Coming soon",
          "Coming soon",
          "Coming soon",
        ],
      },
      {
        id: "pd047",
        name: "Shopify",
        prompt: "",
        value: [
          false,
          false,
          "Coming soon",
          "Coming soon",
          "Coming soon",
          "Coming soon",
        ],
      },
    ],
  },
];
